### PR TITLE
use -cp flag instead of env var

### LINKED ISSUE #402: Powershell launcher errors on big classpath
### Expected behavior
Gauge java project should run successfully

### Actual behavior
Gauge-java's `launcher.ps1` tries to set the CLASSPATH as an environment variable, and for some projects this can exceed the limit set by the OS/shell and result in error such as reported here: https://spectrum.chat/gauge/general/could-not-find-or-load-main-class-com-thoughtworks-gauge-gaugeruntime~df3528dc-82a6-4418-b991-15271177fb32?m=MTU4NDk1Njc3NDIxNQ==

```
C:\Users\xxxxxxxxx\tools\gauge\gauge.exe run --machine-readable --hide-suggestion --simple-console --env abc C:/Users/xxxxxxxxx/IdeaProjects/automationframework\_new/specs/development/blahh/orderhandlingservice/BusinessWorkflow.spec:71
Der Umgebungsvariablenname oder -wert ist zu lang (Environment variable name or value too long)
In C:\Users\xxxxxxxxx\tools\gauge\plugins\java\0.7.4\launcher.ps1:91 Zeichen:5
- $env:CLASSPATH = $global:classpath
- ~~~~~~~~~~~~~~
- CategoryInfo : InvalidOperation: (:) [], ArgumentException
- FullyQualifiedErrorId : ProviderContentWriteError
Fehler: Hauptklasse com.thoughtworks.gauge.GaugeRuntime konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: com.thoughtworks.gauge.GaugeRuntime
```

### Steps to reproduce
Reported by user : https://spectrum.chat/gauge/general/could-not-find-or-load-main-class-com-thoughtworks-gauge-gaugeruntime~df3528dc-82a6-4418-b991-15271177fb32?m=MTU4NDk1Njc3NDIxNQ==

### Dev notes

Instead of setting CLASSPATH environment variable, launch java using `-cp` flag.

### PR DESCRIPTION
**Pull request by sriv**
fixes #402

### CODE REVIEW

**Comment by BugDiver** [comment]
@sriv  I'm not able to recollect properly, but I guess we used to set classpath as env because using it as a flag can exceed the limit of command length.

**Comment by sriv** [comment]
Yes, I think that's going to be a problem too. So what's the way out? The golang launcher was working quite well...

**Comment by negiDharmendra** [comment]
@sriv Using [arguments file](https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-4856361B-8BFD-4964-AE84-121F5F6CF111) might help us solve this problem.

**Comment by sriv** [comment]
Closing this, since this brings in another limitation i.e. command path length

**Pull request closed without merging**
