### PR TITLE
Fix multithreading issue due org.reflections

### PR DESCRIPTION
**Pull request by olivermic-vmob**
Downgraded org.reflections version to 0.9.9
- Reason: https://github.com/getgauge/gauge-java/issues/489

### CODE REVIEW

**Comment by zabil** [comment]
Although this will fix the issue temporarily, it might be a problem to keep track of it as Gauge used dependabot to update and merge libraries automatically. So when this PR is merged dependabot will automatically merge `0.9.11`.

There are pointers at https://github.com/ronmamo/reflections/issues/81#issuecomment-403643630 for a possible fix.

**Comment by sriv** [comment]
There are ways to tell dependabot to ignore certain version/deps: https://dependabot.com/docs/config-file/#ignored_updates

Not sure if we want to do it though, since it would not suggest any updates (even ones in future where this issue may not exist anymore)

**Comment by NivedhaSenthil** [comment]
seems like the issue is fixed via https://github.com/ronmamo/reflections/pull/206 which is released in 0.9.12 ... can you please try upgrading the reflection's version instead on downgrading to see if it solves the problem. If not we could downgrade.

**Comment by olivermic-vmob** [comment]
I tried to upgrade reflections to 0.9.12, but if i now try to `gauge run specs -p -l debug`, it get stuck at "Validation started". I tried to find out why this happens, but was not successful.

**Pull request merged**
