### PR TITLE
Support failing cases

### PR DESCRIPTION
**Pull request by boazberman**
As described in Ref #70 :
# Buy
## Clothes
- Buy a "red" shirt
## Another
- Buy a "" shirt

Will now provide the proper error message.

### CODE REVIEW

**Comment by mahendrakariya** [comment]
Thanks a lot for the PR!! Here are a few observations.

  * Instead of creating a new Exception type, we can just catch `IllegalArgumentException` and set appropriate error message.
  * On [StepExecutionStage.java#L108](https://github.com/boazberman/gauge-java/blob/d639a394d9eefcdc7930e5e7435407cbc01a9442/src/main/java/com/thoughtworks/gauge/execution/StepExecutionStage.java#L108), the `else if` starts on the line after the braces. We generally follow a style where we start `else` on the same line as the closing brace.
  * In the [code](https://github.com/boazberman/gauge-java/blob/d639a394d9eefcdc7930e5e7435407cbc01a9442/src/main/java/com/thoughtworks/gauge/execution/StepExecutionStage.java#L111), there is a catch for `Exception` type, which is generally not a good idea. I understand that this has been around for a while, and is not something that you have implemented. But since you may end up touching that part of code, we would highly appreciate if you could clean it up.

**Comment by boazberman** [comment]
@mahendrakariya I've finally had time to address the issues you brought up. I've fixed what I could to your conciliation, but I'm not thrilled with the style decisions made in this project. There is no Clean Code applied, as well as I would love to see a simple formatter for eclipse being published to help me format my code correctly. And would like to address a few issues:
1.  As you wrote: "In the code, there is a catch for Exception type, which is..." is due to some design decisions taken, making an interface return Exception class. I would be thrilled to wrap all of the code in a new exception type, but that would be in contrast to your code standard (which is wrong to my opinion) as addressed in your first bullet.
2. The method StepExecutionStage.executeStepMethod is huge and requires a refactor, as seen by the very much complex tests. Again it is the cause of a certain code style, that need to be addressed.
2. I've added a test to cover the pull request.

Thanks!

**Comment by mahendrakariya** [comment]
@boazberman We follow Sun Coding standards, with a few minor changes. To enforce coding standards for the project, we have added [`checkstyle.xml`](https://github.com/getgauge/gauge-java/blob/master/checkstyle.xml) file to the repo, which is forked from [`checkstyle/sun_checks.xml`](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml). We have also integrated style audit with the build life cycle. 

On your machine, you can use the [Eclipse Checkstyle plugin](http://eclipse-cs.sourceforge.net/#!/) and configure it to pick the styles from `checkstyle.xml`. This will ensure that Eclipse formats the code based on these styles.

If you have some suggestions for the coding standards, feel free to send us a PR with relevant changes in `checkstyle.xml`.

> a new exception type, but that would be in contrast to your code standard

We haven't enforced any coding standards for catching `Exception` as of now. But in general, catching a generic `Exception` type is a bad practice. There are a few such try/catch blocks in the codebase, which is a tech debt and it needs to be cleaned up.

> I would be thrilled to wrap all of the code in a new exception type

Could you give us more details about this? What is the new exception type you are thinking about and what all would be wrapped in it? If the proposal is promising, we will be more than happy to implement it.

> The method StepExecutionStage.executeStepMethod is huge and requires a refactor

Totally agree! Would you like to take a stab at refactoring it?

**Comment by boazberman** [comment]
@mahendrakariya The branch is now passing. I would be thrilled if you could merge it. Afterwards I will take a beat at refactoring StepExecutionStage.executeStepMethod. Thanks!

**Comment by mahendrakariya** [comment]
@boazberman Thanks a lot for changes!

Wherever there are formatting changes (due to checkstyle), the diff shows the entire file as changed, which is not the actual case. So could you please separate out the formatting commits from the actual commits? Post this, we will merge this PR.

**Pull request closed without merging**
