### PR TITLE
added parameter errorMessage in StepDetails

### PR DESCRIPTION
**Pull request by MolineroUA**
this pull request is an example of what expected for issue https://github.com/getgauge/gauge-java/issues/125

### CODE REVIEW

**Comment by BugDiver** [comment]
@MolineroUA  We appreciate your contribution. There is a [CLA](https://gauge-cla.herokuapp.com/) in place. Could you please sign it so we can start looking into your PR.

**Comment by gaugeci** [comment]
@cla-bot check if all the contributors of this pull request has signed our CLA.

**Comment by gaugeci** [comment]
@cla-bot check if all the contributors of this pull request has signed our CLA.

**Comment by MolineroUA** [comment]
@BugDiver thank you for quick answer on my pull request. I've already signed CLA.

**Comment by BugDiver** [comment]
@MolineroUA  Your PR looks great. Just one thing which I wanted to point out is all the files changes inside `src/gauge/messages` are auto-generated using `protoc`. Could you please do the required `proto` changes in [gauge-proto](https://github.com/getgauge/gauge-proto) and create a PR it that.  Then you can update the `submodule` and generate the files.
Feel free to give a shout if you need any assistance.

**Comment by MolineroUA** [comment]
it's a link to pr in gauge-proto https://github.com/getgauge/gauge-proto/pull/6
I hope this change is correct

**Comment by BugDiver** [comment]
@MolineroUA  Thanks for the PR! We really appreciate your contribution.

**Pull request merged**
