### PR TITLE
TableRow_Changes

### PR DESCRIPTION
**Pull request by slee016**
Changes and additions to the TableRow class and the addition of a
TableCell class to act as a subset of TableRow.

The changes and additions to the TableRow class:
1. changed the data structure to LinkedHashMap
2. addition of getCellValues() method
3. addition of getTableCells() method.

TableCell class represents a single cell instance and contains the
cell's value and column name.

These changes were implemented to provide ease of use and remove the need
to code the underlying implementation when working with individual cells.
The change in the data structure to a LinkedHashMap and the addition of the
getCellValues() method is to allow us to iterate through a table row more
easily. In addition, the structure gaurantees the order, while not sorting
anything in a table row.

The getTableCells() method and the addition of the TableCell class (to act as
a subset of TableRow) was added to allow ease of use when we would like to access
individual cells, or work with individual cells, but don't want to code the
underlying implementation.

### CODE REVIEW

**Comment by slee016** [comment]
Hello Gauge team,

The specs that I am working with require iterating through table rows, and working with individual cells in the table rows.  The changes I am proposing would hopefully improve ease of use, and hide the underlying code you would need to write in order to iterate through a table row, or grab an individual cell instances. Please let me know what you think. Thank you!

**Comment by mahendrakariya** [comment]
Thanks a lot for the pull request @slee016! The changes you submitted does make sense and will surely help the larger audience. We really appreciate your contribution!

**Comment by Thunderforge** [comment]
@mahendrakariya Should TableRow.getCellValues() be deprecated now that we have TableRow.getTableCells()? Or should we keep both of them available?

**Comment by mahendrakariya** [comment]
@Thunderforge That's interesting. Initially, @apoorvam was also of the same opinion as yours.

Here's what I think.

There may be situations when users simply want to loop through the cell values (without bothering about column names) and process them. For instance, take the following table.

| Acct Number | Joint Acct Holder 1 | Joint Acct Holder 2 | Joint Acct Holder 3 |
|-------------------|---------------------------|---------------------------|---------------------------|
| 1234 | ABC | DEF | GHI |
| 4312 | QWE | RTE | YUT |

A test case can be to check if the account with the given number has the mentioned people as joint account holders. The implementation code could look like this.

```java
List<String> row = row.getCellValues();
int acctNum = row.get(0);
Account acct = AccountService.get(acctNum);
for (int i = 1; i < row.size(); i++) {
    assertThat(acct.getJointHolders()).contains(row.get(i));
}
```

In absence of `getCellValues()`, the above code would look something like this.

```java
List<TableCell> row = row.getTableCells();
int acctNum = row.get(0).getValue();
Account acct = AccountService.get(acctNum);
for (int i = 1; i < row.size(); i++) {
    assertThat(acct.getJointHolders()).contains(row.get(i).getValue());
}
```

As is clearly seen, users will have to call `getValue()` every time they do a `row.get()`. They will also have the extra information of column names, which is not required here.

Similarly, there may be situations, where the column name may also be required along with the cell value.

So, I feel having both the methods is fine. However, I am not sure which of the two APIs will users end up using the most. If a lot of people feel that `getCellValues()` won't be used a lot and the extra complexity of `cell.getValue()` is not too much to deal with, we can remove that method. 

I think we should get more opinions before taking a final call.

**Comment by Thunderforge** [comment]
@mahendrakariya In your second example, I would argue that the column name should still be checked to make sure that no extraneous columns are added. 

    List<TableCell> row = row.getTableCells();
    int acctNum = row.get(0).getValue();
    Account acct = AccountService.get(acctNum);
    for (TableCell cell : row.getTableCells()) {
        if (cell.getColumnName().contains("Joint Acct Holder")) { 
            assertThat(acct.getJointHolders()).contains(cell.getValue());
        }
    }

Still, I suppose it's a matter of preference how much trust should be done for columns that are added.

**Comment by Thunderforge** [comment]
For reference, here is a use case we see ourselves using with this new TableCell API:

    for (TableCell cell : row.getTableCells()) {
        switch (cell.getColumnName().toLowerCase()) {
            case "foo":
                validateFoo(cell.getValue());
                break;
            case "bar":
                validateBar(cell.getValue());
                break;
            case "baz":
                validateBaz(cell.getValue());
                break;
            default:
                throw new IllegalArgumentException("Unrecognized table column '" + cell.getColumnName() + "'");
        }
    }

This way, tables can have their columns arranged in any order, can have column names that are upper or lower case, and can omit certain columns (like Twist could). The previous API doesn't provide us these benefits (for instance, `getCell(String columnName)` doesn't work well if you need to handle either upper or lower case).

We're happy that this new API will be added. If others want to keep the previous API, that's fine too.

**Pull request merged**
