### PR TITLE
replace step placeholders by dynamic parameters values

### PR DESCRIPTION
**Pull request by MolineroUA**
I already contributed the changes for that functionality https://github.com/getgauge/gauge-java/pull/160, but unfortunately it doesn't work as expected.

So, I decided to implement "replacer", which will update placeholders in text step on dynamic parameters values.

### CODE REVIEW

**Comment by NivedhaSenthil** [comment]
Hi @MolineroUA ,

Can you please tell us what was not working for you with #160 and what is expected in more detail ?
It will be better if you can create an issue for the same so that it will be easy to track and test once done.

**Comment by MolineroUA** [comment]
Hi @NivedhaSenthil !

The main goal to have ability to get step text from StepDetails with parameters values.

In case of Static parameters everything is Okay, because step text already contains parameters values, they are specified directly.

In case of Dynamic parameters we have step text with placeholders. And when  **actualStepText** is set to StepDetails, the step text will contain placeholders but not a values, for example "_User \<username\> logged-in from client \<clientTypeName\>_".

When I tried to change **actualStepText** on **parsedStepText** the result was "_User {} logged-in from client {}_". It's not what I expected :) and it's my mistake because I didn't verify what exactly Messages.StepInfo contains.

So, in this PR I implemented functionality which will replace a placeholder on value of dynamic parameter in step text.

**Comment by NivedhaSenthil** [comment]
Yes, using actualStepText and having new field to hold dynamic parameters in StepDetails will be cleaner and easy to do approach. The dynamic parameter values are available in stepInfo within currentExecutionInfo which can be used to update the same. Let us know if you need any help with that.

**Comment by MolineroUA** [comment]
@NivedhaSenthil please verify my pull request. I already implemented new class field dynamicText in StepDetails and functionality for replacing placeholders on dynamic parameters values.

**Pull request merged**
