### PR TITLE
release gauge-java after updating jdk/go versions

### PR DESCRIPTION
**Pull request by sriv**

### CODE REVIEW

**Comment by BrudiBanani** [comment]
Hi @sriv,

don't know if this is the right place to adress my question. Are you aware that the deployment process of version 0.7.16 failed?

**Comment by sriv** [comment]
yes @BrudiBanani - maven deploy failed and I need to investigate why. I am not sure about this error - https://github.com/getgauge/gauge-java/runs/5230636180?check_suite_focus=true#step:9:105

**Comment by BrudiBanani** [comment]
@sriv other people seem to run into this error aswell with version 1.6.10 of nexus-staging-plugin
e.g. https://github.com/Azure/azure-sdk-for-java/issues/27135

**Comment by sriv** [comment]
Thanks @BrudiBanani . I too saw an issue against this plugin - https://issues.sonatype.org/browse/NEXUS-31214?focusedCommentId=1140935&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1140935

The maintainer suggests downgrading to 1.6.8.

I'll get this changed once I break away from the day job

**Comment by sriv** [comment]
This is done now @BrudiBanani - you should now be able to use gauge-java 0.8.0 with the latest changes!

**Pull request merged**
