### PR TITLE
WIP : issue-43 java no error on multiple steps 

### PR DESCRIPTION
**Pull request by maquessime**
@mahendrakariya I need your help to complete that one. I've changed the Messages.proto spec to add another error type (https://github.com/getgauge/gauge-proto/pull/2) but I've used the script to generate the java and go code I got problem on both :
- java : diff was very heavy, I though only corresponding java enum would have been changed
- go : got issue with api_v2.proto, I guess it could be skipped since it's not related?

I've used protoc 2.5.0 in both cases.

### CODE REVIEW

**Comment by apoorvam** [comment]
@maquessime The diff you are seeing is because of difference in versions of `protoc` which is used to generate proto messages. 

We have updated the appropriate versions of protoc to be used for each plugin in the corresponding `genproto.sh` files. For gauge-core, you can use the [protoc beta-3](https://github.com/google/protobuf/releases/tag/v3.0.0-beta-3) and for gauge-java you can use v2.6.1 of protoc. Can you please rebase your fork and try with this?

**Comment by maquessime** [comment]
@apoorvam cool will do that

**Comment by maquessime** [comment]
@apoorvam done 

https://github.com/getgauge/gauge/pull/467 must be merged before merging this one, that's why I've put it as WIP

**Comment by mahendrakariya** [comment]
@maquessime Thanks a lot for updating the PR! 

I haven't taken a detailed look at the diff. I will be doing it tomorrow. But after taking a cursory look, I have a quick feedback.

The PR shows there are 10 commits. Few of them seems like merge commits. Can you please rebase your branch, so that this PR only contains the commits related to #59? Also the master branch will remain clean as there won't be unnecessary forks in the tree.

**Comment by maquessime** [comment]
@mahendrakariya will do. I will close this PR and open a new one with the clean branch.

**Comment by maquessime** [comment]
@mahendrakariya https://github.com/getgauge/gauge-java/pull/60

**Pull request closed without merging**
