### PR TITLE
fix linux packaging

### PR DESCRIPTION
**Pull request by sriv**
- fix os/arch combination when packaging
- bump version -> 0.8.1

### CODE REVIEW

**Comment by BrudiBanani** [comment]
@sriv Thanks for the quick fix! We just switched backed to official gauge yesterday and ran into this issue.
Could the tests be extended to avoid such problems in future?

**Comment by sriv** [comment]
Sure, no worries @BrudiBanani 

>  Could the tests be extended to avoid such problems in future?

This was an error with the build script, which can be a bit tricky to test. If you have any suggestions, I am all ears!

**Comment by BrudiBanani** [comment]
@sriv I just had a quick look and also I did not use github workflows. so just an idea.
IMO the problem is that the artifacts which get pushed are build after the FT, so untested artifacts are pushed. Why not build artifacts at first and use them for function tests instead of building seperatly for every FT? 
I hope you can understand what i mean.

**Comment by sriv** [comment]
@BrudiBanani, thanks, that is actually a good idea. I'll try to refactor the scripts to use the artifacts instead.

**Pull request merged**
